version: 2
jobs:
  build:

    docker:
      - image: oracle/graalvm-ce:20.2.0-java11-ol8

    steps:
      - checkout

      - restore_cache:
          key: scheme4graalvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Install Apache Maven
          command: |
            pushd /tmp
            curl http://ftp.tudelft.nl/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz --out apache-maven-3.6.3-bin.tar.gz
            tar -xzf apache-maven-3.6.3-bin.tar.gz
            popd
            /tmp/apache-maven-3.6.3/bin/mvn -version

      - run:
          name: Install gu tool
          command: $JAVA_HOME/bin/gu install native-image

      - run:
          name: Download dependencies and plugins
          command: /tmp/apache-maven-3.6.3/bin/mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: scheme4graalvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: |
            /tmp/apache-maven-3.6.3/bin/mvn -P coverage \
              clean verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_scheme4graalvm \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.java.source=11 \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml \
              -Dsonar.login=$SONAR_LOGIN

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: scheme4graalvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

workflows:
  version: 2
  build:
    jobs:
      - build
